In [1]:
# run experiments to test the differential privacy rate of noisy gradient descent
from data import *
from gradient_descent import *

In [2]:
# generate data
d1 = 100
d2 = 10
r = 3
m = 5

In [3]:
M = get_random_matrix(d1, d2, r)
observed_M, masks = get_random_samples_per_row(M, m)

In [5]:
# run gradient descent
rank = 3
eta = 0.01
epochs = 5000
noise_var = 2.5
rec_U, rec_V = noisy_gradient_descent(observed_M, masks, rank, eta, epochs, noise_var, gap=100)

0 1.0000013346981522
100 0.4528583937836427
200 0.24797650737578414
300 0.22795299933475183
400 0.21149280157887737
500 0.2297372819023861
600 0.22445899934353106
700 0.21186999931194173
800 0.2115816167619834
900 0.20207303587092323
1000 0.19784987965563036
1100 0.20980411336028154
1200 0.2105884499752418
1300 0.20671556788293388
1400 0.18909132955980043
1500 0.21252548195804177
1600 0.208066299456323
1700 0.21437530582430805
1800 0.21468603800007638
1900 0.20039819387112076
2000 0.20366594037384353
2100 0.21460167956885068
2200 0.23347176964225247
2300 0.2167833952223034
2400 0.20209564221976095
2500 0.2088997039378182
2600 0.2079158969879861
2700 0.21152742749348522
2800 0.21332927518457528
2900 0.2272197456672262
3000 0.22127172675182638
3100 0.2133155879605038
3200 0.22445666104864526
3300 0.22094125250070967
3400 0.2294953767032091
3500 0.23002097875882332
3600 0.22543097487580036
3700 0.21655253596606738
3800 0.2069542211777057
3900 0.2164620712760363
4000 0.3013673634714317
410

In [6]:
# get test error
rec_M = rec_U @ rec_V.T
test_err = get_normalized_error(M, rec_M)
print(test_err)

0.4054636178439139


In [7]:
# analyze projection
u1, d1, vt1 = np.linalg.svd(rec_U @ rec_V.T)
vt1 = vt1[:rank, :]

u2, d2, vt2 = np.linalg.svd(M)
vt2 = vt2[:rank, :]
corr = vt1 @ vt2.T

print(corr)

[[ 0.84258785 -0.4354867  -0.26779434]
 [ 0.39480208  0.8839979  -0.23746571]
 [ 0.36498009  0.04919344  0.87582753]]


In [50]:
d1

array([1.20988393e+01, 1.11416766e+01, 1.02066125e+01, 1.59339779e-15,
       9.79756439e-16, 7.76239889e-16, 6.33330240e-16, 4.04532186e-16,
       3.09277192e-16, 3.89592370e-17])

(3, 10)