In [1]:
# run experiments to test the differential privacy rate of noisy gradient descent
from data import *
from gradient_descent import *

In [26]:
# generate data
d1 = 100
d2 = 10
r = 3
m = 5

In [27]:
M = get_random_matrix(d1, d2, r)
observed_M, masks = get_random_samples_per_row(M, m)

In [47]:
# run gradient descent
rank = 3
eta = 0.01
epochs = 5000
noise_var = 2.5
rec_U, rec_V = noisy_gradient_descent(observed_M, masks, rank, eta, epochs, noise_var, gap=100)

0 0.999996865233534
100 0.5671789718186147
200 0.29711010018342277
300 0.23867821769288333
400 0.22740955311530447
500 0.21008087388856936
600 0.2175795102464449
700 0.22057104452182755
800 0.2182877726865183
900 0.21575976158985402
1000 0.21276164861218494
1100 0.22458479946385737
1200 0.20487640802565757
1300 0.2061169468307373
1400 0.20291437206366425
1500 0.22020569471769258
1600 0.22191301343058634
1700 0.21994942201999612
1800 0.22214009651747513
1900 0.20898647776500853
2000 0.21474162101307398
2100 0.21711487858532438
2200 0.23456143975823568
2300 0.22517327916967453
2400 0.23007082066412066
2500 0.24310120749691178
2600 0.23160476204288954
2700 0.2112588713555925
2800 0.22600815358632112
2900 0.22699182888720723
3000 0.22527267511917887
3100 0.23145571640668808
3200 0.22514865745380422
3300 0.2138632275019347
3400 0.20723150189297224
3500 0.21367967746944624
3600 0.2174038031673437
3700 0.21484311307480508
3800 0.22017986158247843
3900 0.23238416694926392
4000 0.22653765762148

In [48]:
# get test error
rec_M = rec_U @ rec_V.T
test_err = get_normalized_error(M, rec_M)
print(test_err)

0.3431187710201095


In [49]:
# analyze projection
u1, d1, vt1 = np.linalg.svd(rec_U @ rec_V.T)
vt1 = vt1[:rank, :]

u2, d2, vt2 = np.linalg.svd(M)
vt2 = vt2[:rank, :]
corr = vt1 @ vt2.T

print(corr)

[[ 0.98854971 -0.03613384 -0.11066133]
 [ 0.05923924  0.981471    0.17723469]
 [-0.10732822  0.18480052 -0.9746543 ]]


In [50]:
d1

array([1.20988393e+01, 1.11416766e+01, 1.02066125e+01, 1.59339779e-15,
       9.79756439e-16, 7.76239889e-16, 6.33330240e-16, 4.04532186e-16,
       3.09277192e-16, 3.89592370e-17])

(3, 10)