In [1]:
from data import *
from gradient_descent import *

In [13]:
# generate data
d1 = 20
d2 = 10
r = 1
m = 2

M = get_random_matrix(d1, d2, r)

# observed_M, masks = get_random_samples_per_row(M, m)
p = 0.3
observed_M, masks = get_uniformly_random_samples(M, p)

In [14]:
# run gradient descent
rank = 1
eta = 0.02
epochs = 2000
rec_U, rec_V = gradient_descent(observed_M, masks, rank, eta, epochs)

0 1.0000001322261456
1 1.0000000886244644
2 1.000000046060013
3 1.0000000039622252
4 0.9999999617718042
5 0.9999999189321065
6 0.9999998748806397
7 0.999999829040534
8 0.9999997808118621
9 0.9999997295626665
10 0.9999996746195594
11 0.9999996152577525
12 0.9999995506903651
13 0.9999994800568465
14 0.9999994024103435
15 0.9999993167038196
16 0.99999922177472
17 0.9999991163279567
18 0.9999989989169558
19 0.9999988679224885
20 0.9999987215289721
21 0.9999985576978888
22 0.9999983741379265
23 0.9999981682714045
24 0.9999979371964803
25 0.9999976776445855
26 0.9999973859324522
27 0.999997057908028
28 0.9999966888894741
29 0.9999962735963434
30 0.999995806071924
31 0.9999952795955929
32 0.9999946865838877
33 0.9999940184788263
34 0.9999932656218283
35 0.9999924171113619
36 0.9999914606422186
37 0.9999903823240298
38 0.9999891664763375
39 0.9999877953971924
40 0.9999862491018454
41 0.999984505027669
42 0.9999825377009407
43 0.9999803183605588
44 0.9999778145331171
45 0.9999749895530636
46 0.

In [15]:
rec_M = rec_U @ rec_V.T

get_normalized_error(M, rec_M)

0.034709317423998465

In [29]:
# analyze projection of V to the right singular vectors
M_U, M_D, M_Vt = np.linalg.svd(M)

M_D = M_D[:r]
M_Vt = M_Vt[:r, :]

ortho_subspace = np.eye(d2) - M_Vt.T @ M_Vt


In [ ]:
# get the right singular vector subspace of the recovered matrix
r_U, r_D, r_Vt = np.linalg.svd(rec_M)

r_D = r_D[:r]
r_Vt = r_Vt[:r, :]

projection = r_Vt @ ortho_subspace


In [18]:
# transform the matrix in order to learn the (right) subspace

transformed_M, transformed_masks = transform_one_sided(observed_M)

# run symmetric gradient descent

rank = 1
eta = 0.01
epochs = 5000

U = symmetric_gradient_descent(transformed_M, transformed_masks, rank, eta, epochs)

0 0.99999999880124
10 0.9999999949263941
20 0.99999997057584
30 0.9999998126816747
40 0.9999987797721427
50 0.9999920049767757
60 0.9999475351815318
70 0.9996556551740912
80 0.997743933746774
90 0.9854013385077661
100 0.9126526587265077
110 0.6494538236150005
120 0.44242371916733886
130 0.4228023483359686
140 0.41684654532753956
150 0.41038140416681246
160 0.4034739074939658
170 0.3966139636633205
180 0.3903632289498991
190 0.385176794100824
200 0.3812624465726631
210 0.37856062597388435
220 0.37683726696256165
230 0.3758081655239523
240 0.3752251400845589
250 0.37490795027426144
260 0.3747405484695568
270 0.374654149698798
280 0.3746102730540853
290 0.3745882475648874
300 0.37457728187803213
310 0.37457185424075945
320 0.3745691787833126
330 0.3745678637763527
340 0.3745672187527655
350 0.37456690281279603
360 0.374566748216043
370 0.3745666726210524
380 0.3745666356745257
390 0.37456661762333127
400 0.3745666088060518
410 0.37456660449988527
420 0.37456660239709283
430 0.374566601370

In [33]:
get_normalized_error(transformed_M, (M_Vt.T @ M_Vt) * (M_D ** 2), transformed_masks)

3.449779257990124

In [32]:
M_Vt.shape

(1, 10)

In [37]:
u1, d1, vt1 = np.linalg.svd(M.T @ M)

d1

array([5.04061819e+01, 6.30933536e-15, 3.99695904e-15, 3.62769330e-15,
       1.32793770e-15, 4.83291962e-16, 3.40309943e-16, 1.51457120e-16,
       6.01364800e-18, 2.42559860e-18])

In [38]:
u2, d2, vt2 = np.linalg.svd(observed_M.T @ observed_M)

d2

array([9.86731995e+00, 4.21280738e+00, 1.72431009e+00, 1.02375623e+00,
       7.10796945e-01, 3.54127116e-01, 1.50931454e-01, 1.92595072e-02,
       4.18666026e-03, 1.44149814e-04])

[22.39774102  8.12391522  5.86328684  4.92827118  4.05680999  3.49641168
  3.12098834  2.58634983  1.47642536  0.06488009]


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1]])

array([[ 2.18502320e+01, -1.33723028e+00,  5.94052118e-01,
         6.11024225e-01,  6.82486817e-01, -2.76927828e-01,
        -9.60872227e-02,  1.80147630e+00, -1.51960818e+00,
        -2.89067848e-01],
       [-1.33723028e+00,  4.37595250e+00, -5.82734805e-01,
        -7.69226188e-01, -2.49283408e-01,  3.51698551e-02,
         1.58474780e-01, -7.33936207e-01,  9.88375677e-01,
         6.26531224e-02],
       [ 5.94052118e-01, -5.82734805e-01,  6.54996365e+00,
         4.61761888e-01,  3.57334338e-01, -1.13962036e-01,
        -1.48538409e-01,  3.89526064e-01, -1.00619900e+00,
        -1.44477092e+00],
       [ 6.11024225e-01, -7.69226188e-01,  4.61761888e-01,
         5.28055376e+00,  2.66711833e-01, -1.12818878e-01,
        -5.38251432e-01,  1.02425394e-01, -1.14235546e+00,
         0.00000000e+00],
       [ 6.82486817e-01, -2.49283408e-01,  3.57334338e-01,
         2.66711833e-01,  2.50054217e+00, -1.59270351e-02,
        -9.44364357e-01,  3.96830646e-02, -5.47801239e-02,
        -1.

In [23]:
x = observed_M.T @ observed_M

In [24]:
x

array([[ 1.52324853e-01,  3.08938747e-02, -2.35442021e-01,
         0.00000000e+00, -6.61296257e-01,  6.28358393e-03,
         5.91137512e-03, -3.44483183e-01, -3.35203414e-01,
         3.29163962e-01],
       [ 3.08938747e-02,  6.88316359e-01, -2.47062707e-01,
        -1.44026816e-01, -3.39526826e-01,  0.00000000e+00,
         6.65433138e-04,  0.00000000e+00, -5.55334443e-01,
         3.78584050e-01],
       [-2.35442021e-01, -2.47062707e-01,  1.40394653e+00,
         6.06131544e-01,  2.39434447e+00, -7.08528758e-03,
        -2.04496634e-02,  0.00000000e+00,  1.10690206e+00,
        -3.26172483e-01],
       [ 0.00000000e+00, -1.44026816e-01,  6.06131544e-01,
         7.53419057e-01,  8.80087736e-01, -7.21935429e-03,
        -3.62662821e-04,  1.48883325e-01,  2.11824766e-01,
        -1.93030024e-01],
       [-6.61296257e-01, -3.39526826e-01,  2.39434447e+00,
         8.80087736e-01,  7.31998372e+00, -1.30800815e-02,
        -4.68879114e-02,  0.00000000e+00,  2.86064031e+00,
        -4.

In [ ]:
y

In [25]:
u, d, vt = np.linalg.svd(x)

In [26]:
d

array([9.86731995e+00, 4.21280738e+00, 1.72431009e+00, 1.02375623e+00,
       7.10796945e-01, 3.54127116e-01, 1.50931454e-01, 1.92595072e-02,
       4.18666026e-03, 1.44149814e-04])

In [ ]:
observed_M.T @ observed_M

In [ ]:
observed_M

In [13]:
M.T @ M

array([[ 1137.22870235,   768.95361497,  2061.97484386,   804.89746658,
         -555.50132001, -2475.20340317,   958.20598384,  1979.79081517,
         2374.08768906,   202.98609683],
       [  768.95361497,   519.9390947 ,  1394.234077  ,   544.2430492 ,
         -375.61024204, -1673.64453668,   647.90481777,  1338.66415881,
         1605.27368592,   137.25198161],
       [ 2061.97484386,  1394.234077  ,  3738.68532152,  1459.40594406,
        -1007.21143005, -4487.93381684,  1737.37844448,  3589.67272681,
         4304.59509317,   368.04578045],
       [  804.89746658,   544.2430492 ,  1459.40594406,   569.68306407,
         -393.16771044, -1751.87712406,   678.19038269,  1401.23847401,
         1680.31035657,   143.6676675 ],
       [ -555.50132001,  -375.61024204, -1007.21143005,  -393.16771044,
          271.34534671,  1209.06089946,  -468.05421615,  -967.06705423,
        -1159.66897631,   -99.15247874],
       [-2475.20340317, -1673.64453668, -4487.93381684, -1751.87712406,
   

In [ ]:
U

In [ ]:
M_Vt

In [ ]:
U_diag_inv = np.diag(1.0 / np.linalg.norm(U, axis=0))

normalized_U = U @ U_diag_inv

In [7]:
observed_M.T @ observed_M

array([[ 0.85410662,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.03130935,  0.        ,  0.        ],
       [ 0.        ,  0.0137139 , -0.02719183,  0.00657536, -0.01739554,
         0.        ,  0.        , -0.00346338,  0.        ,  0.        ],
       [ 0.        , -0.02719183,  0.86928701, -0.79518353,  1.15235471,
        -1.01473945,  0.        ,  0.00686718,  0.        ,  0.        ],
       [ 0.        ,  0.00657536, -0.79518353,  0.77262504, -1.08078204,
         0.98603364,  0.        , -0.00655326,  0.        , -0.01187837],
       [ 0.        , -0.01739554,  1.15235471, -1.08078204,  1.73518105,
        -1.40218356,  0.        ,  0.        ,  0.        ,  0.31087082],
       [ 0.        ,  0.        , -1.01473945,  0.98603364, -1.40218356,
         1.44595685,  0.        ,  0.        ,  0.        , -0.01541074],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        

In [6]:
masks

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [ ]:
normalized_U

In [ ]:
M_Vt @ normalized_U

In [20]:
M.T @ M

array([[ 2.60511081e-01,  9.98485944e-01, -8.60254518e-01,
        -8.76532120e-01, -2.06632471e+00,  2.13369316e-02,
         1.54990679e-01, -1.60200101e+00, -1.38086951e+00,
         1.33820750e+00],
       [ 9.98485944e-01,  3.82699337e+00, -3.29718045e+00,
        -3.35956919e+00, -7.91980199e+00,  8.17801157e-02,
         5.94047723e-01, -6.14014376e+00, -5.29259176e+00,
         5.12907696e+00],
       [-8.60254518e-01, -3.29718045e+00,  2.84071538e+00,
         2.89446696e+00,  6.82337641e+00, -7.04583919e-02,
        -5.11807142e-01,  5.29009591e+00,  4.55987988e+00,
        -4.41900224e+00],
       [-8.76532120e-01, -3.35956919e+00,  2.89446696e+00,
         2.94923561e+00,  6.95248728e+00, -7.17915946e-02,
        -5.21491477e-01,  5.39019428e+00,  4.64616122e+00,
        -4.50261791e+00],
       [-2.06632471e+00, -7.91980199e+00,  6.82337641e+00,
         6.95248728e+00,  1.63896974e+01, -1.69240513e-01,
        -1.22935680e+00,  1.27067695e+01,  1.09527963e+01,
        -1.

In [21]:
observed_M.T @ observed_M

array([[ 1.52324853e-01,  3.08938747e-02, -2.35442021e-01,
         0.00000000e+00, -6.61296257e-01,  6.28358393e-03,
         5.91137512e-03, -3.44483183e-01, -3.35203414e-01,
         3.29163962e-01],
       [ 3.08938747e-02,  6.88316359e-01, -2.47062707e-01,
        -1.44026816e-01, -3.39526826e-01,  0.00000000e+00,
         6.65433138e-04,  0.00000000e+00, -5.55334443e-01,
         3.78584050e-01],
       [-2.35442021e-01, -2.47062707e-01,  1.40394653e+00,
         6.06131544e-01,  2.39434447e+00, -7.08528758e-03,
        -2.04496634e-02,  0.00000000e+00,  1.10690206e+00,
        -3.26172483e-01],
       [ 0.00000000e+00, -1.44026816e-01,  6.06131544e-01,
         7.53419057e-01,  8.80087736e-01, -7.21935429e-03,
        -3.62662821e-04,  1.48883325e-01,  2.11824766e-01,
        -1.93030024e-01],
       [-6.61296257e-01, -3.39526826e-01,  2.39434447e+00,
         8.80087736e-01,  7.31998372e+00, -1.30800815e-02,
        -4.68879114e-02,  0.00000000e+00,  2.86064031e+00,
        -4.

In [ ]:
np.linalg.norm(projection)

In [ ]:
np.linalg.norm(U, 'fro')

In [ ]:
x = observed_M.T @ observed_M

In [ ]:
observed_M.shape

In [ ]:
u, d, vt = np.linalg.svd(M)

In [ ]:
d

In [ ]:
M

In [ ]:
observed_M