In [1]:
import numpy as np
import random
from data import get_random_matrix, get_uniformly_random_samples
from gradient_descent import symmetric_noisy_gradient_descent
from nuclear_norm_min import nuclear_norm_minimization

In [2]:
# instance parameters
d = 100
r = 5
p = 5 * d * r / (d**2)

In [4]:
U = get_random_matrix(d, d, r)

A = U @ U.T

values, S = get_uniformly_random_samples(A, p)

non_zero_indices = np.nonzero(np.array(S))

#print(non_zero_indices)

array([ 0,  5,  9, ..., 74, 90, 96])

set up noisy gradient descent update

In [4]:
eta = 0.001
epochs = 500
noise_var = 5.0
reg = 0.0
init_scale = 0.01

X = symmetric_noisy_gradient_descent(values, S, d, eta, epochs, noise_var, reg, init_scale)

dist = np.linalg.norm(X @ X.T - A, 'fro') / np.linalg.norm(A, 'fro')
print(dist)

0 0.9999948913966363
10 0.999647052505581
20 0.9976777636123931
30 0.9871472588343735
40 0.9326717386493204
50 0.7547039759287443
60 0.5183405337058805
70 0.33114735800721024
80 0.21203107338402513
90 0.14454960867959724
100 0.10387103500703179
110 0.07815564730566447
120 0.061464092795134796
130 0.04954764028839425
140 0.04147323315321769
150 0.03526424193087595
160 0.030864261230443373
170 0.027607438496011518
180 0.024898336382773546
190 0.02272146386148321
200 0.021573369666685886
210 0.020333135675993704
220 0.019756952111046708
230 0.019347759704251743
240 0.018614931962742966
250 0.018801605409240717
260 0.019247356328220853
270 0.01848932859626358
280 0.018635697841311697
290 0.018717142381997367
300 0.01890506559709134
310 0.01883465386419646
320 0.018855503011828013
330 0.018803426978570674
340 0.018996202649029206
350 0.01916704798485906
360 0.019282870835900037
370 0.01933247513244365
380 0.019043758784237422
390 0.0192058556696757
400 0.01910548414142721
410 0.019353420344

In [ ]:
np.linalg.norm(X, 'fro')

In [ ]:
np.linalg.norm(U, 'fro')

with regularization

In [15]:
reg = 10.00

X_reg = symmetric_noisy_gradient_descent(values, S, d, eta, epochs, noise_var, reg)

dist = np.linalg.norm(X_reg @ X_reg.T - A, 'fro') / np.linalg.norm(A, 'fro')
print(dist)

0 1.5455290020071932
10 0.5616873905315056
20 0.34796064866486215
30 0.26402236567155674
40 0.223579535501039
50 0.20233184216072247
60 0.189470703997715
70 0.18179036923174485
80 0.1769256125763358
90 0.17323201798266583
100 0.17107031381318952
110 0.16844378623786402
120 0.16722807335402076
130 0.16530505476842888
140 0.1643735847280897
150 0.1636664435276074
160 0.162783284075077
170 0.16059454176243732
180 0.1600367999480291
190 0.16061024230298845
200 0.15906425111730405
210 0.15800595150738875
220 0.1566677451536908
230 0.15665883635194647
240 0.15590092138669392
250 0.15603771443955283
260 0.1555371619995383
270 0.15477774806525504
280 0.15400396890897985
290 0.1542032298815183
300 0.15353978653621497
310 0.15325742276955615
320 0.15356782406919106
330 0.15294798684898323
340 0.15309967905512437
350 0.15265588425020085
360 0.15283322309609487
370 0.15323784247733097
380 0.15245239941942507
390 0.15244613726702147
400 0.15217680558574234
410 0.15235622500447044
420 0.152018162272

In [ ]:
np.linalg.norm(X_reg, 'fro')

nuclear norm minimization

In [17]:
noise_var = 5
perturbation = np.random.normal(0, 1, (d, d)) * noise_var
zero_matrix = np.zeros_like(perturbation)
zero_matrix[non_zero_indices] = perturbation[non_zero_indices]

perturbed_values = values +zero_matrix

In [18]:
X_nuc, nuc_val = nuclear_norm_minimization(perturbed_values, non_zero_indices)

In [12]:
dist = np.linalg.norm(X_nuc - A, 'fro') / np.linalg.norm(A, 'fro')
print(dist)

0.045238488557398426


In [20]:
values

array([[  0.        ,   0.        ,   0.        , ...,  -0.        ,
          6.43809251,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,  -0.        ,
          4.60830833,  12.19557497],
       [  0.68616078,   0.        ,   0.        , ...,  -0.14165739,
          0.        ,   3.27670323],
       ...,
       [-11.64320443,  -8.50906976,  -0.        , ...,   0.        ,
         -0.        ,  -3.86209488],
       [  0.        ,   0.        ,   0.        , ...,  -0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,  -0.        ,
          0.        ,  11.54101931]])

In [19]:
perturbed_values

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          1.46515961,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          6.05334918,   3.76217461],
       [  6.40752573,   0.        ,   0.        , ...,  -2.57194208,
          0.        ,   4.34626813],
       ...,
       [ -7.00485043, -16.55403318,   0.        , ...,   0.        ,
          0.        ,   1.45920053],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,  16.91899731]])